logging:
  file: "./bin/8mar5d-hub.log"
  level: "debug"

http:
  host: "0.0.0.0"
  port: 6080
  bodyLimit: 1048576

clients:
  devices:
      host: "/dev/ttyUSB0"

metrics:
  devices:
    interval: "1s"